# Generated by Django 2.1.7 on 2019-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('news', models.TextField(blank=True)),
            ],
        ),
    ]
